### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by acasey98** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#1]
## User Story
As a developer, I need to create the files to build the _Kiss The Goat_ website. 

## AC
**WHEN** I open clone the git repo,
**THEN** I should see a directory that contains index.html, main.css, main.js, and README.md
**AND** it should also contain 3 additional sub directories (i.e. imgs, screenshots, & pages)

## Development
* create README.md and add # title
* create index.html and add boilerplate, main.css link (see next step), bootstrap css links, and bootstrap js links. Also add h1 that says hello, and danger button from bootstrap to text functionality.
* create main.css, and make body background-color: lightgray
* create main.js, and add console log to text that it is linked to the index.html
* mkdir imgs; mkdir screenshots; mkdir pages

**Comment by jpantana** [comment]
Bootstrap links here:
https://getbootstrap.com/docs/4.3/getting-started/introduction/

**Comment by zoeames** [comment]
👍
