### ISSUE TITLE
Research - map feature

### ISSUE THREAD

**Issue by emilykdewitt** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#17]
## User Story
As a developer, I need to know how to integrate a dynamic map function into my page that allows the user to see the location of my business on a map and also interact with the map to zoom in or out and see what's in the surrounding area.

## Acceptance Criteria
**WHEN** I open this issue
**THEN** I will see documentation on dynamic maps in the comments below
**AND** see example screenshots of how to display the map on a website.

## Development
* Research how to integrate this feature and add documentation in comments below
* Find examples of how map features are displayed on websites and paste them into comments below

**Comment by zoeames** [comment]
This is going to be VERY difficult to do at this point in the class - it will require an API.  Put this ticket absolutely last.

**Comment by emilykdewitt** [comment]
Thanks! We decided that I would spend 10-15 minutes researching and if it was too complicated, we would just have a static image of the location on a map.

**Comment by emilykdewitt** [comment]
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3222.393140738528!2d-86.75879268470213!3d36.13263981268999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88646609ffab37eb%3A0x528b2eab4ef5110e!2s500+Interstate+Blvd+S%2C+Nashville%2C+TN+37210!5e0!3m2!1sen!2sus!4v1553956615459!5m2!1sen!2sus" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

**Comment by emilykdewitt** [comment]
More information on how to embed a map into a page:
https://www.w3schools.com/tags/att_iframe_src.asp

**Comment by zoeames** [comment]
👍
