### ISSUE TITLE
Implement Bootstraps Carousel and loop over images for index.html

### ISSUE THREAD

**Issue by jpantana** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#18]
## User Story
As a user, when I am viewing the home page of the site, I should see a carousel with images circulating 

## AC
**WHEN** I am viewing the homepage 
**THEN** I should see a bootstrap carousel 
**AND** it should be looping over images

## Development
* Copy Bootstrap code into html
* Research ticket created for this: #21
* create an object array that includes two key/value pairs: captions & images
*  call a function globally (called inside of ```init();```) that loops over the items in said object array
  * use a method to delay each image (research ticket will discover if such a method exists), and design the function in such a way that each item occupies the same space, but at different times.
* finish this function by calling the ```printToDom();``` function so that the images in captions appear on index.html from load.
* add any additional styling to the bootstrap carousel

**Comment by jpantana** [comment]
``` html
<div class="bd-example">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="..." class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="..." class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="..." class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

```

**Comment by zoeames** [comment]
this ticket needs more detail in the development section.  I am assuming you are going to add the detail after you do the research ticket?  If so that ticket should be referenced in this one.

**Comment by jpantana** [comment]
<img width="458" alt="homePageMockUp" src="https://user-images.githubusercontent.com/40041062/55196120-6f808900-517c-11e9-957f-6f692efef3b1.png">

**Comment by zoeames** [comment]
👍
