### ISSUE TITLE
navBar loads in the init

### ISSUE THREAD

**Issue by acasey98** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#19]
## User Story
As a user, when I visit the 'checkout' page of the Kiss the Goat website, I would like to see a navigation bar at the top of the page that allows me to navigate to other pages of the site from the 'checkout' page.

## AC
WHEN the 'checkout' page loads
THEN a navbar with the Kiss the Goat logo and links to other Kiss the Goat pages appears at the top of the page
AND when I click the links, the corresponding page loads

## Development
Take the js function from #6 (index.html navbar creation) that creates the navbar and add it to the init function to fire upon page load for checkout.html and print to 
```html
<div id="navbar"></div> 
```
in checkout.html

**Comment by zoeames** [comment]
this ticket is missing information

**Comment by zoeames** [comment]
👍
