### ISSUE TITLE
map feature

### ISSUE THREAD

**Issue by emilykdewitt** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#2]
## User Story
As a user, when the 'Taproom' page loads, a static image of the brewery's location on a map will appear as an image that is left-aligned under the navbar and half the width of the window.

## Acceptance Criteria
**WHEN** the 'Taproom' page loads
**THEN** a map that displays the location of the brewery will display as a banner under the navbar

## Development
* Add a 'mapContainer' div to the `taproom.html` document
* Add a 'printMap' function that uses `printToDom` to add the map to the page upon page load

### Branch
`e-taproom-map`

**Comment by zoeames** [comment]
Adding this dynamically is going to be very hard.  If you get to this ticket hard code everything in the html

**Comment by emilykdewitt** [comment]
Edited ticket to insert a static image of the location on a map instead of a dynamic map.

**Comment by emilykdewitt** [comment]
![mock-up beer pgae](https://user-images.githubusercontent.com/47046126/55176522-44337500-514f-11e9-8c86-77d630036c1e.png)

**Comment by zoeames** [comment]
👍

**Comment by emilykdewitt** [comment]
> Adding this dynamically is going to be very hard. If you get to this ticket hard code everything in the html

Did you just mean that I shouldn't try print it to the DOM using a JS function?

Here are the instructions I was planning to use:

1. Open Google Maps.
2. Go to the directions, map, or Street View image you'd like to embed.
3. In the top left, click Menu Menu.
4. Click Share or embed map.
5. Click Embed map.
6. To the left of the text box, pick the size you want by clicking the Down arrow Down Arrow.
7. Copy the text in the box. Paste it into the HTML of your website or blog.
