### ISSUE TITLE
Implement bootstrap form for email subscribe on index.html

### ISSUE THREAD

**Issue by jpantana** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#20]
## User Story 
As a user, when I am viewing the home page (index.html), I should be able to enter my email into the input bar and click subscribe

## AC
**WHEN** i load the homepage
**THEN** I should see a form where i can add my email address
**AND** when I click "subscribe" I should be added to an array
**AND** when I click "subscribe" an alert should notify me of my new reality

## Development
* Bootstrap form
* Create an empty array in the JS global scope
* Add a click event listener to receive the email address when submit is clicked
* have a function that creates an object and then pushes the data to the global array
*create an alert 'You've been added to our mailing list!' upon button click.

**Comment by jpantana** [comment]
``` html
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>```

**Comment by zoeames** [comment]
how does the user know their email address has been successfully added?  What feedback comes after they click the submit button

**Comment by emilykdewitt** [comment]
Josh--I think this is as simple as creating an alert 'You've been added to our mailing list!' upon button click.

Then the A/C can be changed to: "**AND** when I click subscribe, I should see an alert that I've been added to the mailing list."

**Comment by zoeames** [comment]
👍
