### ISSUE TITLE
create an "about" section on index.html

### ISSUE THREAD

**Issue by jpantana** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#22]
## User Story
As a user, when I am on the homepage, I should see the about section and a brewery team photo. Bio copy should be charming, fascinating, inspiring, and cause a great number of people to both laugh and cry. 

## AC
**WHEN** people read the bio
**THEN** they should be overwhelmed with emotion
**AND** it should be in a responsive div beneath the carousel

## Development
* create div on html that exists as the child of a .container div
* set an img that fits (responsivley) to the left of the bio on large screens, and above on small sreens

**Comment by jpantana** [comment]
<img width="458" alt="homePageMockUp" src="https://user-images.githubusercontent.com/40041062/55119707-ea846980-50c0-11e9-9272-bb514d675213.png">

**Comment by zoeames** [comment]
lol this ticked overwhelmed me with emotion just reading it
👍

**Comment by jpantana** [comment]
Excellent!

Best,

Josh Pantana
615-974-9879

**Comment by zoeames** [comment]
👍
