### ISSUE TITLE
Change quantity of beer in cart

### ISSUE THREAD

**Issue by acasey98** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#25]
## User Story

As a user, I want to be able to change the quantity of beer that I would like to purchase at checkout.

## AC
**WHEN** The user wants to change how many 6 packs they want
**THEN** They should be able to specify a number and click 'Change' to change the 'quantity' property of the corresponding `shoppingCartArray` object.

## Development
* The printed card from `printCart` should have a form labeled 'Change quantity' that allows the user to input an int greater than -1 (default 0)
* There should be a button next to the 'Change quantity' form labeled 'Change' that takes the current user form input and overwrites the 'quantity' property of the corresponding beer's array object in `shoppingCartArray`, then runs `printCart` to display changes made.

**Comment by zoeames** [comment]
your conversation with keith is going to cause you to change some of this

**Comment by zoeames** [comment]
👍
