### ISSUE TITLE
Cart fa fa that counts (backlog) index.html navBar STRETCH GOAL

### ISSUE THREAD

**Issue by jpantana** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#26]
## User Story
As a user, when I add items to my checkout page, a top-left icon of a cart will have a number that increases with each addition

## AC
**WHEN** a user adds an item to their cart,
**THEN** that item is reflected by a counting function incrementing atop a fa fa icon in the nav bar. 

## Development
* research ticket created #27 (this is a stretch goal)
* add rel links for fontawesome

**Comment by zoeames** [comment]
is this a duplicate of #27?

**Comment by jpantana** [comment]
#27 is the research ticket for this. I'll clarify that above
