### ISSUE TITLE
Research fa fa cart item counter in nav bar for

### ISSUE THREAD

**Issue by jpantana** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#27]
## User Story
As a user, when I click "add to cart" button, a cart icon in the top left of nav bar should be incrementally counting with each item

## AC
**WHEN** i click "add to cart"
**THEN** a cart icon in nav bar should have a number that incrementally counts reflecting how many individual items are in my cart

## Development 
* link rel for font awesome
* position the fa fa class in the nav bar accordingly 
* call a function when _cartArray_ is printed to the dom (e.g. ```cartIcon();```)
* function should looks something like:
  *  ```const cartIcon = () => { let num = array.length; printToDom('cardIconId', num);};``` 
* possibly adding the ```data-count=""``` to the html will be of use (maybe 🤷🏻‍♂️)

**Comment by zoeames** [comment]
For this case you shouldn't need a counter.  Just use the cart.length.  You will always want this number to match the number of things in your array exactly.  Please rework the development section to account for this change

**Comment by jpantana** [comment]
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

For inspiration: https://codepen.io/chcculle/pen/qPrWBK
