### ISSUE TITLE
navBar loads upon page load

### ISSUE THREAD

**Issue by emilykdewitt** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#4]
## User Story
As a user, when I visit the 'Taproom' page of the Kiss the Goat website, I would like to see a navigation bar at the top of the page that allows me to navigate to other pages of the site from the 'Taproom' page.

## Acceptance Criteria
**WHEN** the 'Taproom' page loads
**THEN** a navbar with the Kiss the Goat logo and links to other Kiss the Goat pages appears at the top of the page
**AND** when I click the links, the corresponding page loads

## Development
* Take the js function from #6 (index.html navbar creation) that creates the navbar and add it to the `init` function to fire upon page load for `taproom.html` and print to `<div id="navbar"></div>` in `taproom.html`

### Branch
`e-taproom-navbar`

**Comment by emilykdewitt** [comment]
<img width="558" alt="Screen Shot 2019-03-26 at 8 07 37 PM" src="https://user-images.githubusercontent.com/47046126/55115127-c0777b00-50b1-11e9-86ef-2797f9665f57.png">

**Comment by zoeames** [comment]
👍

**Comment by emilykdewitt** [comment]
![mock-up beer pgae](https://user-images.githubusercontent.com/47046126/55176324-ee5ecd00-514e-11e9-828d-e60bfbc906fd.png)
