### ISSUE TITLE
bootstrap cards list the beers that the user has in their cart, and the appropriate properties

### ISSUE THREAD

**Issue by acasey98** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#5]
## User Story
As a user, I want to see the beers that I have selected for purchase displayed in cards that detail the beer name, beer image, cost per pack, and quantity selected for purchase.

## AC
**WHEN** the checkout page is visited
**THEN** appropriate properties of each object with quantity > 0 should be printed to the top of the DOM as BS4 cards with: beer name, beer image, price per pack, and quantity.

## Development
* implement appropriate BS4 links for the css and js
* implement a BS4 navBar and footer placeholder
* create a function called `printCart` that uses a `forEach` loop to loop through the `shoppingCartArray` for each `beer`, then prints the appropriate properties (name, image, price per, quantity) to a card, but only if the 'quantity' property is greater than 0

**Comment by acasey98** [comment]
![moqupbeer](https://user-images.githubusercontent.com/47999479/55123314-03e0e200-50d0-11e9-96c9-cff4d306a522.PNG)

**Comment by zoeames** [comment]
@acasey98 talk with kieth about this ticket.  You should both really be creating a new array for the shopping cart.  talk about what that array is going to look like so he can make sure he is putting things in that array for you.  That way you will know what dummy data to put in the array so you can start working

**Comment by zoeames** [comment]
👍
