### ISSUE TITLE
index.html navBar creation

### ISSUE THREAD

**Issue by jpantana** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#6]
## User Story
As a user, when I load the site's homepage (and hopefully am at least 21), I should see a responsive nav bar at the top of the screen.

## AC
**WHEN** I agree to the modal's age prompt and the site loads,
**THEN** I should see a responsive nav bar at the top of the page
**AND** the nav bar should point to the other pages on the site

## Development
* implement bootstrap nav bar into index.html and style additionally
  * share placeholder bootstrap navBar (in comments below) with my team (ticket #20)
* add href links (# will point no where for now)
  * "Home", "Tap Room", "The LiBeery" ("Checkout" page will only be accessible from the product page)
* implement bootstrap nav bar into index.html and style additionally

**Comment by jpantana** [comment]
``` html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#">Features</a>
      <a class="nav-item nav-link" href="#">Pricing</a>
      <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
    </div>
  </div>
</nav>
```

**Comment by zoeames** [comment]
is the over 21 modal going to be part of this ticket?  if so can you provide details for how that is going to work in your development section

**Comment by jpantana** [comment]
I totally forgot to add it. yes, it will be my stretch goal at the end for homePage label. Thanks

Best,

Josh Pantana
615-974-9879

**Comment by zoeames** [comment]
👍
