### ISSUE TITLE
Contact/location info

### ISSUE THREAD

**Issue by emilykdewitt** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#7]
## User Story
As a user, when I visit the taproom page of the website, I should see the address, hours, phone number, and a link to schedule a tour at the top of the page located to the right of the map.

## Acceptance Criteria
**WHEN** the 'Taproom' page loads
**THEN** the address, hours, phone number, and a link to schedule a brewery tour will be displayed to the right of the dynamic map
**THEN** when I click the 'Schedule a tour' link, a prompt appears that says 'Your request for a tour has been sent!'

## Development
* Use bootstrap to add a container that will contain the map feature and the directions/info box
* Use bootstrap to style the elements inside the container
* Add an alert feature in JavaScript that will display the message 'Your request for a tour has been sent!'
* Use additional CSS styling to make the elements inside the container look nice

### Branch
`e-taproom-contactinfo`

**Comment by zoeames** [comment]
can you add a wireframe to the ticket?

**Comment by emilykdewitt** [comment]
<img width="558" alt="wireframe" src="https://user-images.githubusercontent.com/47046126/55175551-82c83000-514d-11e9-943b-bd2c80c0f207.png">

**Comment by emilykdewitt** [comment]
![mock-up beer pgae](https://user-images.githubusercontent.com/47046126/55176233-c3747900-514e-11e9-9217-5f6660485b24.png)

**Comment by zoeames** [comment]
👍
