### ISSUE TITLE
Create hover status over employee photo that shows bio

### ISSUE THREAD

**Issue by emilykdewitt** [nss-evening-cohort-9/foundations-group-project-kiss-the-goat#9]
## User Story
As a user, when I hover over an employee photo card, I want an info card to appear over the photo that has the employee's name, hometown, and favorite beers. I can hide the info and make the photo visible again by moving off of the employee photo.

## Acceptance Criteria
**WHEN** I hover my mouse over a photo
**THEN** a card will appear over the photo showing the employee's name, hometown, and favorite beers
**THEN** when I move off of the employee photo, the info disappears

## Development
* Use the documentation provided in card #16 to add the necessary functions and styling
* _This card will be updated later with further instructions on what this feature will require_

**Comment by zoeames** [comment]
👍
